---
title: "R Notebook"
output: html_notebook
---


Load dependencies
```{r}
library(biomaRt)
library(corrplot)
library(circlize)
library(dplyr)
library(tidyverse)
```


Load dendro mappings and select cohort samples
```{r}
mappings <-read.delim("~/Box/Ding_Lab/Projects_Current/CPTAC/CPTACIII/CPTAC3_pancancer_PTM/Analysis/forAkshay/ResultsFromGadGroup/full_dendro_sig_mappings.tsv")

colnames(mappings)<-c("Sample","d1","d3","d17","d22","d39","d54","d56","d5","d11","d29","d40","d24","d36","d13","d38","d19","d2","d6","d9","d10","d14","d18","d28","d20","d31","d25","d43","d23","d37","d33","d4","d7","d15","d21","d32","d8","d16","d26","d34","d12","max_id","max_norm","cohort")

dendro <-c("d1","d3","d17","d22","d39","d54","d56","d5","d11","d29","d40","d24","d36","d13","d38","d19","d2","d6","d9","d10","d14","d18","d28","d20","d31","d25","d43","d23","d37","d33","d4","d7","d15","d21","d32","d8","d16","d26","d34","d12")

for(g in dendro) {
    mappings[,g][mappings[,g]!=""] <- 1
}

d1_samples <- mappings$Sample[mappings$d1=='1']
```

Load acetylation data and convert refseq IDs to HGNC IDs
```{r}
##select histone sites
acetyl <- read.delim("../../../data/acetylome_imputed.tsv")

mart <- useMart(biomart = "ensembl", dataset = "hsapiens_gene_ensembl")

refseq_ids <- unique(acetyl$short_refseq_id)

IDs <- getBM(attributes = c("hgnc_id","refseq_peptide"),
             filters = "refseq_peptide", values = refseq_ids,
             mart = mart)

colnames(IDs)[2] <- 'short_refseq_id'

acetyl<-dplyr::left_join(acetyl,IDs,by='short_refseq_id')
```

Load histone genes and compute mean acetylation levels for each group

```{r}
histone_genes=read.delim('../../../data/Histone_genes_v1.tsv')
hist_acetyl_full <- acetyl %>%
    merge(., histone_genes, by='hgnc_id') %>%
    filter(grepl('histones', gene_type))

h1_acetyl <- hist_acetyl_full %>% filter(gene_type=='H1 histones') %>%
    .[,colnames(.) %in% c('id', d1_samples)] %>%
    column_to_rownames('id') %>% t %>%
    as.data.frame %>%
    mutate(mean=rowMeans(.))

h2a_acetyl <- hist_acetyl_full %>% filter(gene_type=='H2A histones') %>%
    .[,colnames(.) %in% c('id', d1_samples)] %>%
    column_to_rownames('id') %>% t %>%
    as.data.frame %>%
    mutate(mean=rowMeans(.))

h2b_acetyl <- hist_acetyl_full %>% filter(gene_type=='H2B histones') %>%
    .[,colnames(.) %in% c('id', d1_samples)] %>%
    column_to_rownames('id') %>% t %>%
    as.data.frame %>%
    mutate(mean=rowMeans(.))

h3_acetyl <- hist_acetyl_full %>% filter(gene_type=='H3 histones') %>%
    .[,colnames(.) %in% c('id', d1_samples)] %>%
    column_to_rownames('id') %>% t %>%
    as.data.frame %>%
    mutate(mean=rowMeans(.))

h4_acetyl <- hist_acetyl_full %>% filter(gene_type=='H4 histones') %>%
    .[,colnames(.) %in% c('id', d1_samples)] %>%
    column_to_rownames('id') %>% t %>%
    as.data.frame %>%
    mutate(mean=rowMeans(.))

mean_acetyl_df <- data.frame(Sample=rownames(h1_acetyl), h1_acetyl$mean, h2a_acetyl$mean, h2b_acetyl$mean, h3_acetyl$mean, h4_acetyl$mean)
rownames(mean_acetyl_df) <- NULL
```

Plot
```{r}
col_fun = colorRamp2(c(-1, 0, 1), rev(brewer.pal(3,"RdBu")))

colnames(mean_acetyl_df)[-1] <- c('Mean H1 acetyl', 'Mean H2A acetyl', 'Mean H2B acetyl', 'Mean H3 acetyl', 'Mean H4 acetyl')


pdf('S5A.pdf', width=6, height=6)
corrplot(cor(mean_acetyl_df[,-1], method='spearman'), method='color', addCoef.col='black', tl.col='black', col=rev(brewer.pal(10,"RdBu")))
dev.off()
```



```


