---
title: "R Notebook"
output: html_notebook
---


```{r}
library(dplyr)
library(circlize)
library(RColorBrewer)
```

```{r}
x = readRDS('../../data/dendro_tumor_raw_v4_impute_iter100_enzyme_acetyl_full_111322.Rds')

x = x$all_samples

dendro_enzyme_acetyl <-x %>%
    as.data.frame %>%
    mutate(lasso_min_l_MSE=as.numeric(lasso_min_l_MSE)) %>%
    filter(Enzyme_gene!='(Intercept)') %>%
    group_by(Enzyme_gene, Substrate_site) %>%
    mutate(min_MSE=min(lasso_min_l_MSE)) %>%
    mutate(lasso_coef=as.numeric(lasso_coef)) %>%
    filter(abs(lasso_coef) > 0.2, Enzyme_gene!=Substrate_site,lasso_min_l_MSE==min_MSE) %>%
    mutate(substrate_gene=strsplit(Substrate_site, split='\\.NP') %>% lapply(., '[[', 1) %>% unlist) %>%
    mutate(substrate_acetylsite=strsplit(Substrate_site, split='\\.K') %>% lapply(., '[[', 2) %>% unlist) %>%
    mutate(substrate_acetylsite=paste0('K', substrate_acetylsite)) %>%
    mutate(abbrev_substrate_id=paste0(substrate_gene, '-', substrate_acetylsite)) %>%
    group_by(abbrev_substrate_id, Enzyme_gene) %>%
    mutate(avg_lasso_coef=mean(lasso_coef, na.rm=T)) %>%
    as.data.frame %>%
    .[,c('Enzyme_gene', 'substrate_gene', 'substrate_acetylsite', 'abbrev_substrate_id', 'avg_lasso_coef')] %>%
    filter(Enzyme_gene!=substrate_gene) %>%
    distinct %>%
    mutate(split_acetylsite=strsplit(substrate_acetylsite, split='k') %>% lapply(., '[[', 1) %>% unlist) %>%
    mutate(ac_site_position=tidyr::extract_numeric(split_acetylsite))
```

```{r}
plot_enzyme_acetyl <- dendro_enzyme_acetyl %>%
  filter(!(substrate_gene %in% c('BRD1', 'KAT7', 'EP300'))) %>%
  mutate(hist_group=ifelse(grepl('H1', substrate_gene), 'H1', NA)) %>%
  mutate(hist_group=ifelse(grepl('H2', substrate_gene), 'H2', hist_group)) %>%
  mutate(hist_group=ifelse(grepl('H3', substrate_gene), 'H3', hist_group)) %>%
  mutate(hist_group=ifelse(grepl('H4', substrate_gene), 'H4', hist_group)) %>%
  mutate(enz_group=ifelse(Enzyme_gene %in% c('CREBBP', 'NCOA1', 'NCOA3', 'EP300', 'HAT1', 'KAT7', 'MCM3AP'), 'Acetyltransferase', NA)) %>%
  mutate(enz_group=ifelse(grepl('H1|H2|H3|H4', Enzyme_gene), 'Histones', enz_group)) %>%
  mutate(enz_group=ifelse(grepl('BRD', Enzyme_gene), 'BRD', enz_group)) %>%
  mutate(enz_group=ifelse(grepl('HDAC', Enzyme_gene), 'HDAC', enz_group))
  
#rename select histones to match varmap
plot_enzyme_acetyl$Enzyme_gene <- str_replace(plot_enzyme_acetyl$Enzyme_gene, 'H4C15', 'H4-16')
plot_enzyme_acetyl$Enzyme_gene <- str_replace(plot_enzyme_acetyl$Enzyme_gene, '\\.', '\\-')
plot_enzyme_acetyl$substrate_gene <- str_replace(plot_enzyme_acetyl$substrate_gene, '\\.', '\\-')
```


Plot
```{r}

max_val = max(abs(plot_enzyme_acetyl$avg_lasso_coef))
global_lasso_plot <- ggplot(plot_enzyme_acetyl, aes(x=Enzyme_gene, y=abbrev_substrate_id))+
  geom_point(pch=21, aes(fill=avg_lasso_coef, size=5))+
  scale_fill_gradientn(colours=rev(brewer.pal(11,"RdBu")), limits=c(-max_val, max_val))+
  labs(x='', y='Substrate acetylsite', fill='Lasso coefficient')+
  facet_grid(space='free', scales='free', cols=vars(enz_group), rows=vars(hist_group))+
  theme_bw()+
  theme(axis.text.x=element_text(vjust = 0.5,hjust=0.95, angle=90), legend.position = 'right')+
  scale_size(guide='none')


out_dir <- 'figures/'

pdf(paste0(out_dir, 'global_lasso_bubble_plot_120922.pdf'), width=8, height=6)
print(global_lasso_plot)
dev.off()

```



