---
title: "R Notebook"
output: html_notebook
---
```{r}
library(dplyr)
library(ggplot2)
```

Load imputed data used for lasso
```{r}
test.master <-readRDS("../../data/test.maste_raw_impute.Rds")
mappings <-read.delim("../../data/cluster_map.tsv")


ac_plot_sites <- c('H2BC18.NP_001154806.1.K17kK21k')
pro_plot_ids <- c('CREBBP')

out_dir <- 'figures/'

for (group in c('all_samples','C22')) {
    
    if (group=='all_samples') {
        plot_ac_pro <- test.master[,c('cluster_id',pro_plot_ids, ac_plot_sites)] 
    } else {
        plot_ac_pro <- test.master[,c('cluster_id',pro_plot_ids, ac_plot_sites)] %>% filter(cluster_id==group)
    }
    
    p <- ggplot(plot_ac_pro, aes(x=CREBBP, y=H2BC18.NP_001154806.1.K17kK21k))+
        geom_point(size=1, alpha=0.5)+
        #scale_color_manual(values=c('True'='#311B92', 'False'='#F9A825'))+
        geom_smooth(method=lm, na.rm = TRUE, fullrange= T, se=F,
                    aes(group=1),colour="black", size=0.5)+
        labs(x='CBP', y='H2B-K12K13k')+
        theme_classic()
    
    pdf(paste0(out_dir, group, '_CBP_H2B_scatter.pdf'), width=4, height=3)
    print(p)
    dev.off()
    
}

```

```{r}
### NCOA1, H2Bc3 K16K17k (C12)
ac_plot_sites <- c('H2BC3.NP_066406.1.K16kK17k')
pro_plot_ids <- c('NCOA1')

group='C12'
plot_ac_pro <- test.master[,c('cluster_id',pro_plot_ids, ac_plot_sites)] %>% filter(cluster_id==group)

p <- ggplot(plot_ac_pro, aes(x=NCOA1, y=H2BC3.NP_066406.1.K16kK17k))+
    geom_point(size=1, alpha=0.5)+
    #scale_color_manual(values=c('True'='#311B92', 'False'='#F9A825'))+
    geom_smooth(method=lm, na.rm = TRUE, fullrange= T, se=F,
                aes(group=1),colour="black", size=0.5)+
    labs(x='NCOA1', y='H2B-K16K17k')+
    theme_classic()

pdf(paste0(out_dir, group, '_NCOA1_H2B_scatter.pdf'), width=4, height=3)
print(p)
dev.off()
```

```{r}

## BRD4, H2BC18-K17kK21k (C7)
ac_plot_sites <- c('H2BC18.NP_001154806.1.K17kK21k')
pro_plot_ids <- c('BRD4')

group='C7'
plot_ac_pro <- test.master[,c('cluster_id',pro_plot_ids, ac_plot_sites)] %>% filter(cluster_id==group)

p <- ggplot(plot_ac_pro, aes(x=BRD4, y=H2BC18.NP_001154806.1.K17kK21k))+
    geom_point(size=1, alpha=0.5)+
    #scale_color_manual(values=c('True'='#311B92', 'False'='#F9A825'))+
    geom_smooth(method=lm, na.rm = TRUE, fullrange= T, se=F,
                aes(group=1),colour="black", size=0.5)+
    labs(x='BRD4', y='H2B-K17K21k')+
    theme_classic()

pdf(paste0(out_dir, group, '_BRD4_H2B_scatter.pdf'), width=4, height=3)
print(p)
dev.off()
```

```{r}
## TAF1 H2B-K21 (C9)

ac_plot_sites <- c('H2BC3.NP_066406.1.K21k')
pro_plot_ids <- c('TAF1')

group='C9'
plot_ac_pro <- test.master[,c('cluster_id',pro_plot_ids, ac_plot_sites)] %>% filter(cluster_id==group)

p <- ggplot(plot_ac_pro, aes(x=TAF1, y=H2BC3.NP_066406.1.K21k))+
    geom_point(size=1, alpha=0.5)+
    #scale_color_manual(values=c('True'='#311B92', 'False'='#F9A825'))+
    geom_smooth(method=lm, na.rm = TRUE, fullrange= T, se=F,
                aes(group=1),colour="black", size=0.5)+
    labs(x='TAF1', y='H2B-K21k')+
    theme_classic()

pdf(paste0(out_dir, group, '_TAF1_H2B_scatter.pdf'), width=4, height=3)
print(p)
dev.off()
```


